

CREATE TABLE IF NOT EXISTS `category`
(
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `CATEGORY_NAME` varchar(40),
    `CREATION_DATE` TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS `product`
(
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESCRIPTION` VARCHAR(128),
    `CATEGORY_ID` int,
    `CREATION_DATE` TIMESTAMP,
    `UPDATE_DATE` TIMESTAMP,
    `LAST_PURCHASED_DATE` TIMESTAMP
    );

ALTER TABLE product ADD FOREIGN KEY (CATEGORY_ID) REFERENCES category(id) ON UPDATE CASCADE ON DELETE CASCADE;


