INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (1, 'Kitchen',CURRENT_TIMESTAMP );
INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (2, 'Power Tools',CURRENT_TIMESTAMP);
INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (3, 'Furniture',CURRENT_TIMESTAMP);
INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (4, 'Electric',CURRENT_TIMESTAMP);
INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (5, 'Washroom',CURRENT_TIMESTAMP);
INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (6, 'Textiles',CURRENT_TIMESTAMP);
INSERT INTO category (id, CATEGORY_NAME, CREATION_DATE) VALUES (7, 'Misc.',CURRENT_TIMESTAMP);

